# Generated by Django 5.2.1 on 2025-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Support name')),
                ('email', models.EmailField(max_length=254, verbose_name='Support email')),
                ('text', models.TextField(verbose_name='Support text')),
            ],
        ),
    ]
