# Generated by Django 5.2.1 on 2025-05-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mobile name')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Mobile image')),
                ('price', models.PositiveIntegerField(verbose_name='Mobile price')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_Mobile', to='main.brand')),
            ],
            options={
                'verbose_name': 'mobile',
                'verbose_name_plural': 'mobiles',
            },
        ),
    ]
